version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/minutes90
      - TokenKey=your-super-secret-key-with-at-least-32-characters-for-production
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=minutes90
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 